// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(obj, alias, actual) {
    if (!obj[actual] && obj[alias]) {
      obj[actual] = obj[alias];
      delete obj[alias];
    }
    return obj;
  };

}).call(this);
